### ISSUE TITLE
Unresolved dependencies path

### ISSUE THREAD

**Issue by pme123** [Kremlianski/sortable-js-facade#1]
I want to try your facade, but no luck so far:

sbt update gives me:
net.scalapro#sortable-js-facade_sjs0.6_2.11;0.2.1: not found

**Comment by pme123** [comment]
The problem seems to be that I use Scala 2.11.8.

**Comment by Kremlianski** [comment]
Thank you for interest in my little lib
Yes! I didn't build it for 2.11 but only for 2.12. 
If you don't want to use Scala 2.12 you can compile this project by yourself.
