### ISSUE TITLE
Library maintenance

### ISSUE THREAD

**Issue by mathieuleclaire** [Kremlianski/sortable-js-facade#3]
Hi Alexandre,
do you still maintain this lib ? I did a PR last year with no answer; I need to upgrade the lib toward scala 2.13. Would you promote me as maintener so that I could upgrade libs on the fly and release new versions ?

Thanks
Mathieu

**Comment by Kremlianski** [comment]
Hi, Mathieu! You've been invited as a collaborator 

https://github.com/Kremlianski/sortable-js-facade/invitations

Regards

**Comment by mathieuleclaire** [comment]
Thanks !

**Comment by mathieuleclaire** [comment]
Hi Alexandre,
I pushed a 0.3.0 (with 2.13.1 support). Would you be kind as publishing it ?
Thanks !
Mathieu

**Comment by mathieuleclaire** [comment]
Hi Alexandre,
I tried to push new commits for scalajs 1.0 and it seems I don't have permissions any more. Could you please check this ? Then a 0.3 release and publish is ready.
Mathieu

**Comment by mathieuleclaire** [comment]
Hi @Kremlianski ,
could you have a look to my collaborator permission ? I can't push any more (see previous message).
Thanks !

**Comment by mathieuleclaire** [comment]
@Kremlianski ?

**Comment by mathieuleclaire** [comment]
Well, I have to fork the lib then.
